import keyMirror from "keymirror";

export default keyMirror({
  BUTTON_CLICKED: null,
  BUTTON_INITIALIZED: null,
  INPUT_ENTERED: null,
  STRING_INPUT_INITIALIZED: null,
  NUMERIC_INPUT_INITIALIZED: null,
  DROPDOWN_INITIALIZED: null,
  CHECKBOX_INITIALIZED: null,
  OUTPUT_INITIALIZED: null,
  USER_LOGIN_ATTEMPTED: null,
  USER_REGISTRATION_COMPLETED: null,
});
